// frontend/src/app/features/agents/ui/citation-list/citation-list.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { Citation } from '../../models/agent.model';

@Component({
  selector: 'app-citation-list',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="flex flex-col gap-2.5 max-w-full">
      @for (c of citations(); track $index) {
        <div class="bg-app border border-border hover:border-border-strong rounded-xl p-3.5 transition-all duration-200">
          <div class="flex items-center gap-2 mb-1.5">
            <lucide-icon name="file-text" class="w-4 h-4 text-text-muted"></lucide-icon>
            <span class="text-xs font-bold text-text-primary truncate max-w-[90%]">
              {{ c.source_document }}
            </span>
            @if (c.score) {
              <span class="text-[10px] font-medium border border-success/30 bg-success/10 text-success px-1.5 py-0.5 rounded-full ml-auto">
                {{ (c.score * 100).toFixed(0) }}% khớp
              </span>
            }
          </div>
          <p class="text-xs text-text-secondary italic leading-relaxed line-clamp-3 hover:line-clamp-none transition-all duration-300">
            "{{ c.content }}"
          </p>
        </div>
      }
    </div>
  `
})
export class CitationListComponent {
  citations = input.required<Citation[]>();
}

// frontend/src/features/chat/ui/CitationList.tsx
import { FileText } from "lucide-react";

import type { Citation } from "../types/chat";

interface CitationListProps {
  citations: readonly Citation[];
}

export function CitationList({ citations }: CitationListProps) {
  return (
    <ul aria-label="Message citations" className="grid gap-2.5">
      {citations.map((citation, index) => (
        <li className="rounded-ui-panel border border-ui-line bg-ui-raised p-3" key={`${citation.source_document}-${index}`}>
          <div className="flex items-start gap-2">
            <FileText aria-hidden className="mt-0.5 h-4 w-4 shrink-0 text-ui-ink-muted" />
            <p className="min-w-0 flex-1 truncate text-xs font-bold text-ui-ink">
              {citation.source_document}
            </p>
            {citation.score === undefined ? null : (
              <span className="shrink-0 rounded-full border border-state-success bg-state-success-soft px-2 py-0.5 text-[0.6875rem] font-semibold text-state-success">
                {Math.round(citation.score * 100)}% match
              </span>
            )}
          </div>
          <p className="mt-2 text-xs italic leading-5 text-ui-ink-secondary">{citation.content}</p>
        </li>
      ))}
    </ul>
  );
}
