// frontend/src/features/topics/ui/TopicCard.tsx
import { ArrowUpRight, FileStack, Gauge } from "lucide-react";
import { Link } from "react-router-dom";

import type { Topic, TopicStatus, TopicType } from "../types/topic";

const statusLabels: Record<TopicStatus, string> = {
  active: "Active",
  archived: "Archived",
  needs_review: "Needs review",
};

const statusTones: Record<TopicStatus, string> = {
  active: "border-state-success bg-state-success-soft text-state-success",
  archived: "border-ui-line bg-ui-canvas text-ui-ink-secondary",
  needs_review: "border-state-warning bg-state-warning-soft text-state-warning",
};

const typeLabels: Record<TopicType, string> = {
  domain: "Domain",
  subtopic: "Subtopic",
  topic: "Topic",
};

export function TopicCard({ topic }: { topic: Topic }) {
  return (
    <Link
      className="group flex min-h-56 flex-col rounded-ui-panel border border-ui-line bg-ui-raised p-5 shadow-ui-card transition-colors duration-200 hover:border-ui-line-strong hover:bg-ui-interactive focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand"
      to={`/dashboard/topics/${topic.topic_id}`}
    >
      <div className="flex items-start justify-between gap-4">
        <div className="flex flex-wrap gap-2">
          <span className="rounded-ui-status border border-ui-line px-2.5 py-1 text-xs font-semibold text-ui-ink-secondary">
            {typeLabels[topic.type]}
          </span>
          <span
            className={`rounded-ui-status border px-2.5 py-1 text-xs font-semibold ${statusTones[topic.status]}`}
          >
            {statusLabels[topic.status]}
          </span>
        </div>
        <ArrowUpRight
          aria-hidden
          className="h-5 w-5 shrink-0 text-ui-ink-muted transition-colors duration-200 group-hover:text-brand"
        />
      </div>

      <h2 className="mt-5 text-xl font-semibold tracking-tight text-ui-ink">
        {topic.name}
      </h2>
      <p className="mt-2 line-clamp-3 flex-1 text-sm leading-6 text-ui-ink-secondary">
        {topic.summary ?? "No summary is available yet."}
      </p>

      <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 border-t border-ui-divider pt-4 text-sm text-ui-ink-muted">
        <span className="inline-flex items-center gap-2">
          <FileStack aria-hidden className="h-4 w-4" />
          {topic.evidence_count} evidence
        </span>
        <span className="inline-flex items-center gap-2">
          <Gauge aria-hidden className="h-4 w-4" />
          {Math.round(topic.confidence * 100)}% confidence
        </span>
      </div>
    </Link>
  );
}

// frontend/src/app/features/topics/ui/topic-card/topic-card.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LucideAngularModule } from 'lucide-angular';
import { TranslateModule } from '@ngx-translate/core';
import { Topic } from '../../../../core/models/topic.model';

@Component({
  selector: 'app-topic-card',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule, TranslateModule],
  template: `
    <div
      [routerLink]="['/dashboard/topics', topic().topic_id]"
      class="bg-surface border border-border hover:border-primary/40 rounded-xl p-5 cursor-pointer transition-all duration-300 hover:shadow-md flex flex-col justify-between h-[200px] select-none group relative overflow-hidden">
      
      <!-- Hover overlay effect -->
      <div class="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"></div>
      
      <div class="space-y-3 relative z-10">
        <!-- Header: Type & Status Badges -->
        <div class="flex items-center justify-between gap-2 shrink-0">
          <span
            class="px-2 py-0.5 rounded text-[11px] font-semibold uppercase tracking-wider bg-primary-soft text-primary border border-primary/20">
            {{ topic().type }}
          </span>
          
          <!-- Status Badge -->
          @if (topic().status === 'active') {
            <span class="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">
              {{ 'TOPICS.STATUS_ACTIVE' | translate }}
            </span>
          } @else if (topic().status === 'needs_review') {
            <span class="px-2 py-0.5 rounded text-[11px] font-semibold bg-amber-500/10 text-amber-600 border border-amber-500/20 animate-pulse">
              {{ 'TOPICS.STATUS_NEEDS_REVIEW' | translate }}
            </span>
          } @else {
            <span class="px-2 py-0.5 rounded text-[11px] font-semibold bg-text-muted/10 text-text-muted border border-border">
              {{ 'TOPICS.STATUS_ARCHIVED' | translate }}
            </span>
          }
        </div>

        <!-- Topic Name -->
        <h3 class="text-base font-bold text-text-primary group-hover:text-primary transition-colors duration-200 line-clamp-1">
          {{ topic().name }}
        </h3>

        <!-- Topic Summary -->
        <p class="text-xs text-text-secondary line-clamp-3 leading-relaxed">
          {{ topic().summary || ('TOPICS.NO_TOPICS' | translate) }}
        </p>
      </div>

      <!-- Footer Info -->
      <div class="flex items-center justify-between pt-3 border-t border-border/60 shrink-0 text-text-muted text-[11px] relative z-10">
        <!-- Evidence Count -->
        <span class="flex items-center gap-1">
          <lucide-icon name="database" class="w-3.5 h-3.5"></lucide-icon>
          <strong>{{ topic().evidence_count || 0 }}</strong> {{ 'TOPICS.RELEVANCE' | translate }}
        </span>
        
        <!-- Confidence Score -->
        <span class="flex items-center gap-1">
          <lucide-icon name="sparkles" class="w-3.5 h-3.5 text-primary"></lucide-icon>
          {{ 'TOPICS.CONFIDENCE_SCORE' | translate }}: <strong>{{ (topic().confidence * 100) | number:'1.0-0' }}%</strong>
        </span>
      </div>
    </div>
  `
})
export class TopicCardComponent {
  topic = input.required<Topic>();
}
