// frontend/src/features/agents/ui/AgentCard.tsx
import { MessageSquare, PencilLine, Trash2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

import type { AgentDetail } from "../types/agent";
import { AgentAvatarIcon } from "./agent-appearance";
import { getAgentAvatarColor } from "./agent-avatar-color";

interface AgentCardProps {
  agent: AgentDetail;
  canManage: boolean;
  deleteDisabled?: boolean;
  onDelete: (agent: AgentDetail) => void;
}

export function AgentCard({ agent, canManage, deleteDisabled = false, onDelete }: AgentCardProps) {
  const { t } = useTranslation();

  return (
    <article className="group flex h-full flex-col justify-between rounded-ui-panel border border-ui-divider bg-ui-raised p-5 transition-colors duration-200 hover:border-ui-line-strong motion-reduce:transition-none">
      <div>
        <div className="flex items-start justify-between gap-4">
          <div
            aria-hidden
            className={`flex h-12 w-12 items-center justify-center rounded-2xl text-white shadow-sm ${getAgentAvatarColor(agent.avatar_color)}`}
          >
            <AgentAvatarIcon className="h-6 w-6" icon={agent.avatar_icon} />
          </div>
          {canManage ? (
            <div className="flex items-center gap-1">
              <Link
                aria-label={t("AGENTS_UI.EDIT_AGENT", { name: agent.name })}
                className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-ui-control text-ui-ink-muted transition-colors hover:bg-ui-interactive hover:text-ui-ink motion-reduce:transition-none"
                to={`/dashboard/agents/${agent.id}/edit`}
              >
                <PencilLine aria-hidden className="h-4 w-4" />
              </Link>
              <button
                aria-label={t("AGENTS_UI.DELETE_AGENT", { name: agent.name })}
                className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-ui-control text-ui-ink-muted transition-colors hover:bg-state-danger-soft hover:text-state-danger motion-reduce:transition-none"
                disabled={deleteDisabled}
                onClick={() => onDelete(agent)}
                type="button"
              >
                <Trash2 aria-hidden className="h-4 w-4" />
              </button>
            </div>
          ) : null}
        </div>

        <h2 className="mt-5 text-lg font-bold text-ui-ink">{agent.name}</h2>
        <p className="mt-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-ui-ink-muted">
          <span aria-hidden className="h-1.5 w-1.5 rounded-full bg-state-success" />
          {t("AGENTS_UI.MODEL_STATUS", { model: agent.model_name })}
        </p>
        <p className="mt-4 line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-ui-ink-secondary">
          {agent.system_prompt}
        </p>
      </div>

      <Link
        aria-label={t("AGENTS_UI.CHAT_WITH", { name: agent.name })}
        className="mt-5 inline-flex min-h-11 items-center justify-center gap-2 rounded-ui-control border border-state-info bg-state-info-soft px-4 py-2 font-semibold text-state-info transition-colors hover:bg-ui-interactive motion-reduce:transition-none"
        to={`/dashboard/agents/${agent.id}/chat`}
      >
        <MessageSquare aria-hidden className="h-4 w-4" />
        {t("AGENTS_UI.START_CONVERSATION")}
      </Link>
    </article>
  );
}

// frontend/src/app/features/agents/ui/agent-card/agent-card.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { Agent } from '../../models/agent.model';

@Component({
  selector: 'app-agent-card',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="bg-surface rounded-2xl border border-border hover:border-border-strong p-6 shadow-soft hover:shadow-soft/50 transition-all duration-300 flex flex-col justify-between h-full group">
      <div>
        <div class="flex items-start justify-between mb-4">
          <!-- Avatar Group -->
          <div [class]="'w-12 h-12 rounded-xl flex items-center justify-center text-white shadow-sm border border-white/10 ' + agent().avatar_color">
            <lucide-icon [name]="agent().avatar_icon" class="w-6 h-6"></lucide-icon>
          </div>
          
          <!-- Actions (chỉ hiển thị khi hover hoặc cho Admin/Owner) -->
          @if (canManage()) {
            <div class="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
              <button 
                (click)="$event.stopPropagation(); edit.emit(agent())"
                class="p-1.5 hover:bg-white/5 text-text-muted hover:text-text-primary rounded-lg transition-colors"
                title="Chỉnh sửa"
              >
                <lucide-icon name="pencil-line" class="w-4 h-4"></lucide-icon>
              </button>
              <button 
                (click)="$event.stopPropagation(); delete.emit(agent())"
                class="p-1.5 hover:bg-error/10 text-text-muted hover:text-error rounded-lg transition-colors"
                title="Xóa"
              >
                <lucide-icon name="trash-2" class="w-4 h-4"></lucide-icon>
              </button>
            </div>
          }
        </div>

        <!-- Info -->
        <h3 class="text-lg font-bold text-text-primary mb-1 group-hover:text-primary transition-colors">
          {{ agent().name }}
        </h3>
        
        <p class="text-xs text-text-muted mb-3 flex items-center gap-1.5">
          <span class="w-1.5 h-1.5 rounded-full bg-text-disabled"></span>
          {{ agent().model_name || 'gemini-2.5-flash' }}
        </p>

        <p class="text-sm text-text-secondary line-clamp-3 mb-6 min-h-[60px]">
          {{ agent().system_prompt }}
        </p>
      </div>

      <!-- Action Button -->
      <button 
        (click)="chat.emit(agent())"
        class="w-full py-2.5 px-4 border border-ai/30 bg-ai-soft text-ai hover:bg-ai/20 rounded-lg text-sm font-semibold transition-all duration-300 flex items-center justify-center gap-2"
      >
        <lucide-icon name="message-square" class="w-4 h-4"></lucide-icon>
        Nhắn tin với Agent
      </button>
    </div>
  `
})
export class AgentCardComponent {
  agent = input.required<Agent>();
  canManage = input<boolean>(false);
  
  edit = output<Agent>();
  delete = output<Agent>();
  chat = output<Agent>();
}
